name = "HTTPack"
author = "bitbloxhub"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b7bb61443b038dc132bebd6381a9a183124a95cd50f9f84da771136fe05b98a1"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
